---
abstract: 'unicode pictogram fallback to html'
author:
  - 'Masayuki Matsuki E<lt>y.songmu@gmail.comE<gt>'
build_requires:
  HTTP::Request::Common: 0
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-UnicodePictogramFallback-TypeCast
no_index:
  directory:
    - inc
provides:
  Plack::Middleware::UnicodePictogramFallback::TypeCast:
    file: lib/Plack/Middleware/UnicodePictogramFallback/TypeCast.pm
    version: 0.02
  Plack::Middleware::UnicodePictogramFallback::TypeCast::EmoticonMap:
    file: lib/Plack/Middleware/UnicodePictogramFallback/TypeCast/EmoticonMap.pm
    version: 0
requires:
  Encode::JP::Mobile: 0
  Encode::JP::Mobile::UnicodeEmoji: 0
  Plack: 1.00
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
